/sub_1/controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    distributed: true
    sub_controller_manager: true
    use_multiple_nodes: true
    distributed_interfaces_publish_period: 12

    export_state_interfaces:
      - "sub_1_joint1/position"
    
    export_command_interfaces:
      - "sub_1_joint1/position"

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
