controller_manager:
  ros__parameters:
    central_controller_manager: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fpc_jtc_chain_controller:
      type: forward_command_controller/ForwardCommandController

fpc_jtc_chain_controller:
  ros__parameters:
    joints:
      - /sub_1/position_trajectory_controller/sub_1_joint_a1
      - /sub_1/position_trajectory_controller/sub_1_joint_a2
      - /sub_1/position_trajectory_controller/sub_1_joint_a3
      - /sub_1/position_trajectory_controller/sub_1_joint_a4
      - /sub_1/position_trajectory_controller/sub_1_joint_a5
      - /sub_1/position_trajectory_controller/sub_1_joint_a6
      - /sub_2/position_trajectory_controller/sub_2_joint_a1
      - /sub_2/position_trajectory_controller/sub_2_joint_a2
      - /sub_2/position_trajectory_controller/sub_2_joint_a3
      - /sub_2/position_trajectory_controller/sub_2_joint_a4
      - /sub_2/position_trajectory_controller/sub_2_joint_a5
      - /sub_2/position_trajectory_controller/sub_2_joint_a6
    interface_name: position