/sub_2/controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    sub_controller_manager: true
    distributed_interfaces_publish_period: 4
    export_command_interfaces:
      - ""
    export_state_interfaces:
      - ""

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

/sub_2/position_trajectory_controller:
  ros__parameters:
    joints:
      - sub_2_joint_a1
      - sub_2_joint_a2
      - sub_2_joint_a3
      - sub_2_joint_a4
      - sub_2_joint_a5
      - sub_2_joint_a6

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 2.0 # Defaults to 50
    action_monitor_rate: 2.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)