/sub_2/controller_manager:
  ros__parameters:
    update_rate: 10  # Hz
    sub_controller_manager: true
    distributed_interfaces_publish_period: 4

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
