publisher_forward_position_controller:
  ros__parameters:
    publish_topic: "/fpc_jtc_chain_controller/commands"
    wait_sec_between_publish: 5

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [0.0, -1.57, 1.57, 0.0, 1.57, 0.0, 0.0, -1.57, 1.57, 0.0, 1.57, 0.0]
    pos2: [0.0, -1.57, 1.57, 0.0, 0.0, 0.0, 0.0, -1.57, 1.57, 0.0, 0.0, 0.0]
    pos3: [0.0, -1.57, 1.57, 0.0, 1.57, 0.0, 0.0, -1.57, 1.57, 0.0, 1.57, 0.0]
    pos4: [0.0, -1.57, 1.57, 0.0, 0.0, 0.0, 0.0, -1.57, 1.57, 0.0, 0.0, 0.0]
